### ISSUE TITLE
Add a unit test to confirm the Node version

### ISSUE THREAD

**Issue by dtribble** [Agoric/PlaygroundVat#10]
Many tests will appear to fail if the user has an old version of node installed (pre 10?). Please add a unit or configuration test to report that accurately when they run `npm test` rather than appearing to have a lot of failing tests.

[This article](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json) describes variants of how to do this, but adding an appropriate tape test might be the most convenient.

**Comment by warner** [comment]
Ok I think that covers it. @dtribble feel free to re-open if there's a workflow that doesn't give a decent error message.
